name: grosshop
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.1
  flutter_staggered_grid_view: ^0.4.1
  animated_text_kit: ^4.1.1
  flutter_credit_card: ^3.0.5
  image_picker: ^0.8.6+4
  google_nav_bar: ^5.0.3
  line_icons: ^2.0.1
  flutter_rating_bar: ^4.0.0
  geolocator: ^9.0.2
  location: ^4.1.1
  http: ^0.13.5
  get: ^4.6.5
  nfc_manager: ^3.2.0
  shared_preferences: ^2.0.18
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.13
  flutter_launcher_icons: ^0.12.0
  flutter_ringtone_player: ^3.2.0
  audioplayers: ^3.0.1
  flutter_local_notifications: ^9.7.0
  flutter_callkit_incoming: ^1.0.3+3
  intl: ^0.18.0
  carousel_slider: ^4.2.1
  intl_phone_field: ^3.1.0
  flutter_paypal: ^0.0.8
  moyasar_payment: ^0.1.5
  money_converter: ^2.0.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon/bgr-logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboard/
    - assets/images/icon/
    - assets/images/discount/
    - assets/images/category/
    - assets/images/grocery/
    - assets/images/card/
    - assets/images/nfc/
    - assets/ringtone/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
